## 应用名称
#spring.application.name=news
## 应用服务 WEB 访问端口
#server.port=1004
##注册中心地址
#eureka.client.serviceUrl.defaultZone=http://localhost:1001/eureka/
#
#juhe.news.key=0738d00fddda8f1273db226b4dc68b14
#wanwei.news.key=986324c42ad044e692e6a3e8fc1e51cd

# 端口
server:
  port: 1004


eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://${eureka.instance.hostname}:1001/eureka/

logging:
  level:
    # log 级别
    org.springframework.cloud: debug

spring:
  application:
    name: news
  #redis配置
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
    timeout: 60s
    jedis:
      pool:
        max-active: -1
        max-idle: 15
        max-wait: -1s
        min-idle: 5
juhe:
  news:
    key: 0738d00fddda8f1273db226b4dc68b14

wanwei:
  news:
    key: 986324c42ad044e692e6a3e8fc1e51cd