## 应用名称
#spring.application.name=stock
## 应用服务 WEB 访问端口
#server.port=1003
##注册中心地址
#eureka.client.serviceUrl.defaultZone=http://localhost:1001/eureka/
#
#baidu.stock.AppCode=e48b8f17825b4d45a4ad807ed501b391
#baidu.stock.AccessKey=6ba0c951319840f8a8f7f4656b5dc4dc
#baidu.stock.AppSecret=e119f9c84a8246518a35c32ce1f64952

# 端口
server:
  port: 1003


eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://${eureka.instance.hostname}:1001/eureka/

logging:
  level:
    # log 级别
    org.springframework.cloud: debug

spring:
  application:
    name: stock


baidu:
  stock:
    AppCode: e48b8f17825b4d45a4ad807ed501b391
    AccessKey: 6ba0c951319840f8a8f7f4656b5dc4dc
    AppSecret: e119f9c84a8246518a35c32ce1f64952
