## 应用名称
#spring.application.name=lifetools
## 应用服务 WEB 访问端口
#server.port=1005
##注册中心地址
#eureka.client.serviceUrl.defaultZone=http://localhost:1001/eureka/



# 端口
server:
  port: 1005


eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://${eureka.instance.hostname}:1001/eureka/

logging:
  level:
    # log 级别
    org.springframework.cloud: debug

spring:
  application:
    name: lifetools
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: mysql
    url: jdbc:mysql://localhost:3306/huoxuan?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password: 123456

#指定Mybatis的Mapper文件
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml